# Properties file with JDBC-related settings.
# Applied by PropertyPlaceholderConfigurer from "dataAccessContext-local.xml".
# Targeted at system administrators, to avoid touching the context XML files.

jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/fctech?useUnicode=true&characterEncoding=utf-8
jdbc.username=root
jdbc.password=root
validationQuery=SELECT 1
#work at company
#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@127.0.0.1:1521:orcl
#jdbc.username=ipsdb
#jdbc.password=ipsdb
min=30
max=100
